package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.5
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BanqueAccountServiceService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/?wsdl")
public class BanqueAccountServiceService
    extends Service
{

    private static final URL BANQUEACCOUNTSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException BANQUEACCOUNTSERVICESERVICE_EXCEPTION;
    private static final QName BANQUEACCOUNTSERVICESERVICE_QNAME = new QName("http://ws/", "BanqueAccountServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUEACCOUNTSERVICESERVICE_WSDL_LOCATION = url;
        BANQUEACCOUNTSERVICESERVICE_EXCEPTION = e;
    }

    public BanqueAccountServiceService() {
        super(__getWsdlLocation(), BANQUEACCOUNTSERVICESERVICE_QNAME);
    }

    public BanqueAccountServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUEACCOUNTSERVICESERVICE_QNAME, features);
    }

    public BanqueAccountServiceService(URL wsdlLocation) {
        super(wsdlLocation, BANQUEACCOUNTSERVICESERVICE_QNAME);
    }

    public BanqueAccountServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUEACCOUNTSERVICESERVICE_QNAME, features);
    }

    public BanqueAccountServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueAccountServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankWS
     */
    @WebEndpoint(name = "BankWSPort")
    public BankWS getBankWSPort() {
        return super.getPort(new QName("http://ws/", "BankWSPort"), BankWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankWS
     */
    @WebEndpoint(name = "BankWSPort")
    public BankWS getBankWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BankWSPort"), BankWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUEACCOUNTSERVICESERVICE_EXCEPTION!= null) {
            throw BANQUEACCOUNTSERVICESERVICE_EXCEPTION;
        }
        return BANQUEACCOUNTSERVICESERVICE_WSDL_LOCATION;
    }

}
